---
title: DougNet
title_font: Fraktur

# can be geopattern or trianglify
background: geopattern

# Links Bar
links:
  - name: philipsd6
    icon: fa-brands fa-github
    url: https://github.com/philipsd6
  - name: philipsd6
    icon: fa-brands fa-instagram
    url: https://www.instagram.com/philipsd6

# Service Cards
services: []
