---
title: Homepage
title_font: Fraktur

# can be geopattern or trianglify
background: trianglify

# Links Bar
links:
  - name: joe
    icon: fa-brands fa-github
    url: https://github.com/joe
  - name: joesothername
    icon: fa-brands fa-instagram
    url: https://www.instagram.com/joesothername

# Service Cards
services:
  - name: Service 1
    logo: https://loremflickr.com/320/240/movie
    url: https://example.com
  - name: Another Service
    logo: https://loremflickr.com/320/240/books
    url: https://example.com
  - name: Anything Really
    logo: https://loremflickr.com/320/240/television
    url: https://example.com
