---
title: DougNet
title_font: Fraktur

background: trianglify
#background: geopattern

# External Links
links:
  - name: philipsd6
    icon: fa-brands fa-github
    url: https://github.com/philipsd6
  - name: philipsd6
    icon: fa-brands fa-instagram
    url: https://www.instagram.com/philipsd6/

services:
  - name: ArgoCD
    logo:
    url:
  - name: Calibre-Web
    logo:
    # or icon: fa-...
    url:
  - name: LazyLibrarian
    logo:
    url:
